- name: Add deadsnakes Python repository
  become: yes
  become_user: root
  apt_repository: repo='ppa:fkrull/deadsnakes'

- name: Remove ubuntugis repository
  become: yes
  become_user: root
  apt_repository: repo='ppa:ubuntugis/ppa' state=absent

- name: Install packages
  become: yes
  become_user: root
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - python3.5
      - python3.5-dev
      - python-virtualenv
      - git
      - unzip
      - libxslt1-dev
      - libxml2-dev
      - libjpeg-dev
      - libgdal-dev
      - libmemcached-dev
      - libffi-dev

- name: dev locale
  become: yes
  become_user: root
  action: command update-locale LC_ALL=en_US.UTF-8

- name: set default locale
  become: yes
  become_user: root
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"en_US.UTF-8\""

- name: Create base directory for virtual environment
  become: yes
  become_user: root
  file: path="{{ virtualenv_path | dirname }}" state=directory
        owner="{{ app_user }}" mode=0755

- name: Manually create the initial virtualenv
  become: yes
  become_user: "{{ app_user }}"
  command: virtualenv {{ virtualenv_path }} --python=python3.5
           creates="{{ virtualenv_path }}bin"

- name: Upgrade to latest PIP version
  become: yes
  become_user: "{{ app_user }}"
  pip: name=pip state=latest virtualenv="{{ virtualenv_path }}"

- name: Install requirements
  become: yes
  become_user: "{{ app_user }}"
  environment:
      C_INCLUDE_PATH: '/usr/include/gdal'
      CPLUS_INCLUDE_PATH: '/usr/include/gdal'
  pip: virtualenv="{{ virtualenv_path }}"
       requirements="{{ application_path }}requirements/common.txt"
       extra_args="--find-links https://s3.amazonaws.com:443/cadasta-wheelhouse/index.html"

- name: Set up logging directory
  become: yes
  become_user: root
  file: path=/var/log/django state=directory owner="{{ app_user }}"

- name: Create temporary data processing directory
  become: yes
  become_user: "{{ app_user }}"
  file: path="{{ application_path }}cadasta/geography/data" state=directory

- name: Download world boundary data files
  become: yes
  become_user: "{{ app_user }}"
  get_url: url=https://cadasta-miscellaneous.s3.amazonaws.com/ne_10m_admin_0_countries.zip
           dest="{{ application_path }}cadasta/geography/data/ne_10m_admin_0_countries.zip"

- name: Unzip world boundary data files
  become: yes
  become_user: "{{ app_user }}"
  unarchive: creates="{{ application_path }}cadasta/geography/data/ne_10m_admin_0_countries.shp"
             src="{{ application_path }}cadasta/geography/data/ne_10m_admin_0_countries.zip"
             dest="{{ application_path }}cadasta/geography/data" copy=no

- name: Django migrate
  become: yes
  become_user: "{{ app_user }}"
  django_manage: command=migrate
                 app_path="{{ application_path }}cadasta"
                 virtualenv="{{ virtualenv_path }}"
                 settings="{{ django_settings }}"

- name: Install Bootstrap for SASS processing
  become: yes
  become_user: "{{ app_user }}"
  command: chdir="{{ application_path }}cadasta/core"
           npm install bootstrap-sass

- name: Write platform identifier to core template file
  become: yes
  become_user: "{{ app_user }}"
  template: src=identifier
            dest="{{ application_path }}cadasta/templates/core/identifier.html"
